version: '3.8'

services:
  app:
    build: .
    container_name: nguyenvansam-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=mongodb://mongo:27017/projectbackend
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123
      - MYSQL_DATABASE=projectbackend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=nguyenvansamthichdangthithuy
    depends_on:
      - mongo
      - mysql
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - backend-network

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: projectbackend
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

volumes:
  mongo-data:
  mysql-data:

networks:
  backend-network:
    driver: bridge
